import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppClerkProvider } from "@/components/providers/app-clerk-provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${geistSans.className} dark h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-base font-sans text-copy-primary">
        <AppClerkProvider>{children}</AppClerkProvider>
      </body>
    </html>
  );
}
